kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: {{ include "bets.fullname" . }}
spec:
  args:
  - name: service-name
  metrics:
  - name: success-rate
    interval: 10s
    successCondition: result[0] >= 0.9
    failureCondition: result[0] < 0.9
    failureLimit: 3
    provider:
      prometheus:
        address: http://prometheus.istio-system:9090
        query: |
          sum(irate(istio_requests_total{reporter="source",destination_service=~"{{args.service-name}}",response_code=~"2.*"}[2m])) / sum(irate(istio_requests_total{reporter="source",destination_service=~"{{args.service-name}}"}[2m]))
