apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: bets-rollout-analysis-step
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
  {{- include "bets.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
    {{- include "bets.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: {{ include "bets.fullname" . }}
          ports:
            - name: http
              containerPort: 9999
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
  strategy:
    canary:
      canaryService: bets-canary
      stableService: bets
      trafficRouting:
        istio:
          virtualService:
            name: bets-vs
            routes:
              - primary
      steps:
        - setWeight: 10
        - pause:
            duration: 2m
        - setWeight: 30
        - pause:
            duration: 60s
        - setWeight: 50
        - pause:
            duration: 60s
      analysis:
        templates:
        - templateName: {{ include "bets.fullname" . }}
        startingStep: 2