apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: bets-rollout-analysis-step
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 2
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "bets.fullname" . }}
  strategy:
    canary:
      canaryService: bets-canary
      stableService: bets-stable
      trafficRouting:
        istio:
          virtualService:
            name: bets-vs
            routes:
              - primary
      steps:
      - setWeight: 10
      - pause:
          duration: 2m
      - setWeight: 30
      - pause:
          duration: 30s
      - setWeight: 50
      - pause:
          duration: 30s
      analysis:
        templates:
        - templateName: {{ include "bets.fullname" . }}
        startingStep: 2